#!/usr/bin/env bash
set -e

################################################################################
# Lint CSS
################################################################################
npm run lint

################################################################################
# Check version numbers
################################################################################
# Get the current Git tag, if any.
GIT_TAG=$(git describe --tags --exact-match 2>/dev/null || echo '[None]')

# Get first version number listed in `README.md`.
README=$(grep -oE '^### v([0-9]+\.){2}[0-9]+' README.md | head -n 1 | sed 's/^### //')

# Get version number in `reset.css`.
CSS=$(grep -oE '^ \* v([0-9]+\.){2}[0-9]+' reset.css | head -n 1 | sed 's/^ \* //')

if [ "$GIT_TAG" != "$README" ] || [ "$README" != "$CSS" ]; then
  echo 'Version mismatch detected:' >&2
  echo "  - Git Tag:   $GIT_TAG" >&2
  echo "  - README.md: $README" >&2
  echo "  - reset.css: $CSS" >&2
  echo 'Please update all version references to match.' >&2
  exit 1
fi

################################################################################
# Validate changelog date
################################################################################
if grep -qE "^### ${README} \([0-9]{4}-[0-9]{1,2}-[0-9]{1,2}\)" README.md; then
  :
else
  echo 'README.md: Missing or invalid date in the Changelog.'
  exit 1
fi

################################################################################
# TO TEST THIS HOOK: uncomment statement below
################################################################################
# exit 1
